### ISSUE TITLE
Mongodb Denial of Service

### ISSUE THREAD

**Issue by rfossella** [emirotin/mongodb-migrations#66]
Hello,
Running npm audit for _mongodb-migrations v0.85_ throws the following warning.  Is there/will there be a package update?  Or best way to address this?  Thanks!
 
node v12.13.0
npm@6.14.11

>npm audit
```
High            Denial of Service
  Package         mongodb
  Patched in      >=3.1.13
  Dependency of   mongodb-migrations
  Path            mongodb-migrations > mongodb
  More info       https://npmjs.com/advisories/1203
```
Package.json dependencies
```
"dependencies": {
    "bluebird": "^3.4.1",
    "lodash": "^4.13.0",
    "mkdirp": "^0.5.1",
    "mongodb": "^2.2.1",
    "nomnom": "^1.6.2"
  },

**Comment by emirotin** [comment]
This package is unmaintained.
You can fork it and update the dependency

**Comment by rfossella** [comment]
thank you

**Comment by rfossella** [comment]
Hello.  Not sure if what I did was what you recommended - i.e. forked, updated, created pull request?  If not, then can you explain?
Thanks.

**Comment by emirotin** [comment]
I'll try to find time to check it out
What I actually meant is you can use your fork, it can be set as a
dependency directly from github

Did you run the tests?

**Comment by rfossella** [comment]
Hmm.  My very preliminary tests looked ok.  A more robust test is throwing errors
```
Unhandled rejection TypeError: this._db.collection is not a function
    at Migrator._coll (C:\Development\wamp64\www\MyApp\src\server\node_modules\mongodb-migrations\lib\mongodb-migrations.js:58:23)
    at C:\Development\wamp64\www\MyApp\src\server\node_modules\mongodb-migrations\lib\mongodb-migrations.js:69:24
    at tryCatcher (C:\Development\wamp64\www\MyApp\src\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Development\wamp64\www\MyApp\src\server\node_modules\bluebird\js\release\promise.js:547:31)
 
When I roll back to the published version (with mongodb 2.2.4) it works.

FYI: the remainder of my application uses 3.6.4

Maybe another conflicting package :\

I'll continue to check; if you have any ideas please let me know.  And thank you for extending yourself to me.  Appreciated!

**Comment by emirotin** [comment]
I would assume a change of api given it's a major version update
There's a test suite in the package
